id: P008017
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD107142
  title: གསུང་འབུམ། ཨོ་རྒྱན་འཇིགས་མེད་ཆོས་ཀྱི་དབང་པོ
  author: ''
  volumes:
    8cb0505cb7d741debb05869c591d2bd4:
      image_group_id: I1PD107144
      title: ''
      volume_number: 1
      total_pages: 582
    4dae0e10ee084a5a893c1fb19a7d843a:
      image_group_id: I1PD107145
      title: ''
      volume_number: 2
      total_pages: 580
    d283605b16ee43d296267e8fa362d728:
      image_group_id: I1PD107146
      title: ''
      volume_number: 3
      total_pages: 382
    5e144207987d43dfba43b1cc2d2c4e4d:
      image_group_id: I1PD107147
      title: ''
      volume_number: 4
      total_pages: 562
    d000dded57964421ade9b64ee91a6cf5:
      image_group_id: I1PD107148
      title: ''
      volume_number: 5
      total_pages: 630
    2c6cdde38580422bba6685258438a222:
      image_group_id: I1PD107149
      title: ''
      volume_number: 6
      total_pages: 494
    e3e2cac73c3e463fa4a1befb57f977c1:
      image_group_id: I1PD107150
      title: ''
      volume_number: 7
      total_pages: 612
    7142cc903cd94892acd7409a38b4b25f:
      image_group_id: I1PD107151
      title: ''
      volume_number: 8
      total_pages: 576
ebook_metadata:
  title: གསུང་འབུམ། ཨོ་རྒྱན་འཇིགས་མེད་ཆོས་ཀྱི་དབང་པོ
  author: ''
  sku: P008017
  cover: cover.jpg
  layers:
  - pagination
