id: IA84AED1A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T22:55:26+00:00'
last_modified: '2022-06-16T06:17:08.731821+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD107142
  title: གསུང་འབུམ། ཨོ་རྒྱན་འཇིགས་མེད་ཆོས་ཀྱི་དབང་པོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6B6B:
      image_group_id: I1PD107144
      title: Volume 1 of gsung 'bum/_o rgyan 'jigs med chos kyi dbang po
      total_pages: 582
      order: 1
      base_file: 6B6B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
